# Generated by Django 4.2.3 on 2023-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemusuario',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='imagemusuario',
            name='nome',
        ),
        migrations.AlterField(
            model_name='imagemusuario',
            name='foto',
            field=models.ImageField(upload_to='imagem/%Y/%m/%d/'),
        ),
    ]
