# Generated by Django 4.2.3 on 2023-07-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0003_alter_imagemusuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemusuario',
            name='nome',
        ),
    ]
