# Generated by Django 4.2.3 on 2023-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0004_remove_imagemusuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemusuario',
            name='categoria',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ESTUDANTE', 'Estudante')], default='', max_length=100, null=True),
        ),
    ]
