# Generated by Django 4.2.3 on 2023-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.CharField(max_length=400)),
                ('link_trailer', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='imagens/%Y/%m/%d')),
            ],
        ),
    ]
