# Generated by Django 4.2.3 on 2023-07-20 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaz',
            name='data_lancamento',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='cartaz',
            name='em_cartaz',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cartaz',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartaz',
            name='sinopse',
            field=models.TextField(max_length=400),
        ),
    ]
