# Generated by Django 4.2.3 on 2023-07-21 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartaz_app', '0002_cartaz_data_lancamento_cartaz_em_cartaz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaz',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartaz',
            name='data_lancamento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cartaz',
            name='em_cartaz',
            field=models.BooleanField(default=False),
        ),
    ]
