# Generated by Django 4.2.3 on 2023-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaz_app', '0003_cartaz_usuario_alter_cartaz_data_lancamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaz',
            name='categoria',
            field=models.CharField(choices=[('ADMINISTRADOR', 'administrador'), ('USUARIO', 'usuario')], default='', max_length=100, null=True),
        ),
    ]
