# Generated by Django 4.2.3 on 2023-07-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaz_app', '0005_cartaz_horario1_alter_cartaz_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaz',
            name='horario2',
            field=models.TimeField(null=True),
        ),
    ]
