# Generated by Django 4.2.3 on 2023-07-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(max_length=100)),
                ('assento', models.CharField(max_length=2)),
                ('forma_pagamento', models.CharField(choices=[('DEBITO', 'debito'), ('CREDITO', 'credito'), ('PIX', 'pix')], default='', max_length=100)),
            ],
        ),
    ]
