# Generated by Django 4.2.3 on 2023-07-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assentos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='forma_pagamento',
            field=models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito à vista'), ('PIX', 'Pix')], default='', max_length=100),
        ),
    ]
